version: '3.4'

volumes:
  reports-db:

services:
  webapi:
    image: vosarat/reports-webapi:1.1
    environment:
      MONGO_CONNECTIONSTRING: mongodb://db:27017
    ports:
    - 7000:80
    depends_on:
      - db
  db:
    image: mongo:3.6.22
    restart: always
    ports:
      - 27030:27017
    volumes:
      - reports-db:/data/db
  events-publisher:
    image: vosarat/reports-events-publisher:1.0
    environment:
      RABBIT_CONNECTIONSTRING: amqp://mq:5672
      WABAPI_URL: http://webapi:80
      EXCHANGEPREFIX: astorindocker.reports
    depends_on:
      - mq
  mq:
    image: rabbitmq:3-management
    ports:
      - 15673:15672
      - 5673:5672
